/*
	myRemotes.h
	Author : Jeronimo Gomez Tantarelli

*/


//COMANDOS DE CONTROL REMOTO GENERICO CAR MP3 REMOTE
//ADDRESS: 00FF
typedef enum{
	CMD_BUTTON_CH_MINUS = 0xA2,
	CMD_BUTTON_CH		= 0x62,
	CMD_BUTTON_CH_PLUS	= 0xE2,
	CMD_BUTTON_PREV		= 0x22,
	CMD_BUTTON_NEXT		= 0x02,
	CMD_BUTTON_PAUSE	= 0xC2,
	CMD_BUTTON_VOL_MINUS= 0xE0,
	CMD_BUTTON_VOL_PLUS	= 0xA8,
	CMD_BUTTON_EQ		= 0x90,
	CMD_BUTTON_FOL_MINUS= 0x98,
	CMD_BUTTON_FOL_PLUS	= 0xB0,
	CMD_BUTTON_0		= 0x68,
	CMD_BUTTON_1		= 0x30,
	CMD_BUTTON_2		= 0x18,
	CMD_BUTTON_3		= 0x7A,
	CMD_BUTTON_4		= 0x10,
	CMD_BUTTON_5		= 0x38,
	CMD_BUTTON_6		= 0x5A,
	CMD_BUTTON_7		= 0x42,
	CMD_BUTTON_8		= 0x4A,
	CMD_BUTTON_9		= 0x52,
	CMD_NONE			= 0x00,
	}myRemoteCMD;
